version: "3.8"

services:
  db:
    image: postgres:15
    container_name: fastapi-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: bookly
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    container_name: fastapi-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  celery:
    build: .
    container_name: fastapi-celery
    restart: always
    depends_on:
      - redis
      - web
    environment:
      CELERY_BROKER_URL: redis://fastapi-redis:6379/0
      CELERY_RESULT_BACKEND: redis://fastapi-redis:6379/0
    networks:
      - app-network

  web:
    build: .
    container_name: fastapi-app
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge