name: Nightly Build

#on:
#  schedule:
#    - cron: "0 0 * * *"  # Runs at 12 AM UTC daily

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        id: test
        run: pytest -v
        continue-on-error: true  # Allows the workflow to continue

      - name: Build & Push Docker Image
        if: success()
        steps:
          - name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Build and Push
            uses: docker/build-push-action@v3
            with:
              push: true
              tags: your-dockerhub-username/bookly:latest

  notify-on-failure:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: failure()  # Only run if tests fail

    steps:
      - name: Send Failure Email via Ethereal SMTP
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          from: ${{ secrets.MAIL_FROM }}
          to: "your-email@example.com"
          subject: "Nightly Build Failed"
          body: "The nightly build has failed. Please check logs."
          content_type: text/plain